language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: gvKk7QzCWyZdmIK/M0RxZBjkjbuO1z19Kh3y3pahB7GXb8FgZ8hUzpbYcAMQvbonN3+e2Jguo1UbmoxALRgHfwiLGzrjqQXl6WthKGxE5JOLdJE5fQAbiTHBPTnUq5lQzU6jTQQ+l/C2fLzwyfu/1KdyV9Cn4kAEZdLTwPm67UMAwwcS70EN51SN7XoAVLjtgZ9A/DtDNk8w2hzXeMTh7i5TPxArCUH0/eXu9D42fYVyEK6EmyHqGjQvg0KZF1yhJR4fK4vJdo89duShmy4d33UrUtpMEUbCwRE3Oo4dgZeiD0NK1qHTPhXOcb/AYisFMv5ICPWIju+A9/c90VGUyox4vPEHwM4NdrwP6GC3n2t496tTPxlKrV5dghDSOWYIWmGOKfvyX4HN2POWLpOGh7sag84oPKLisrN//ho8gQyiNUm1Plg84aF9FHpLRIjpoWnidh7i0heYbYNahS6w9qyYRmMhusTzTNGJ/o3Z/pAPPHPC6EynJQ2I5UfPswYt77KouZ4hXkEtdS66TPh3TbXFJ/iV4YrRSRPIvrpHh6d04CBShvEwikI3j3Ki1jYSfHue+KNQPVBVI2GKa8if0v8Ris78Gq+NW+P7BEWFos2sAWUpR3E7358YVcadri/NHPJgiZF3NeAi8C0qH2MrvxzV32R55pzyPtPTIByExwU=
  app:
    master: hacker-news-clone-sumit
